name = "SommerfeldCZT"
uuid = "78877123-5d51-4198-8424-69974287841c"
version = "0.1.0"
authors = ["Joan Conza <j.conza@pucp.pe>"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[extras]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["QuadGK", "SpecialFunctions", "Test"]

[compat]
julia = "1.10"
FFTW = "1.10"
QuadGK = "2.11.2"
SpecialFunctions = "2.6.1"
